/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codeimpact.swing.jideossimpl;

import com.codeimpact.swing.abstraction.CIInternalFrame;
import com.jidesoft.swing.AutoCompletion;
import com.jidesoft.swing.AutoCompletionComboBox;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author eko
 */
public class JideOSSAutoCompletionIFrame extends CIInternalFrame {

    private List<String> listNama;
    private List<String> listKota;

    /**
     * Creates new form JideOSSAutoCompletionIFrame
     */
    public JideOSSAutoCompletionIFrame() {
        initData();
        initComponents();
        initAutoCompletion();
    }

    private void initData() {
        listNama = new ArrayList<String>(
                Arrays.asList("Eko Suhariyadi", "Hiro Kunimi", "Chiaki Shinichi", "Kudo Shinichi", "Haruka Koga", "Megumi Noda", "Ran Mouri"));
        listKota = new ArrayList<String>(
                Arrays.asList("Sidoarjo", "Surabaya", "Malang", "Madiun", "Jakarta"));
    }

    private void initAutoCompletion() {
        AutoCompletion txtNamaCompletion = new AutoCompletion(txtNama, listNama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboKota = new AutoCompletionComboBox(listKota.toArray());

        setTitle("JIDE OSS AutoCompletion");

        labelName.setText("Nama:");

        jLabel1.setText("Kota:");

        comboKota.setPreferredSize(new java.awt.Dimension(71, 19));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(labelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama)
                    .addComponent(comboKota, 0, 301, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelName)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboKota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelName;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
